Fixed a minor stonithd testing error (not much of a bug)
Mercurial revision: 436a3254ea47a5c3a1f2e85a164947fca0e2726a

diff --git a/fencing/test/STONITHDBasicSanityCheck.in b/fencing/test/STONITHDBasicSanityCheck.in
--- a/fencing/test/STONITHDBasicSanityCheck.in
+++ b/fencing/test/STONITHDBasicSanityCheck.in
@@ -127,7 +127,8 @@ clean_work
 if [ $ERR_COUNT -eq 0 ]; then
 	echo "All tests for stonithd are ok."
 else
-	echo "There are $ERR_COUNT errors when testing stonthd."
+	echo "There are $ERR_COUNT ERRORs when testing stonithd."
+	exit $ERR_COUNT
 fi
 
 exit 0
