Have testProgram() return a simple yes/no Make sure the call to which is in an if-block to avoid trap being invoked
CVS patchset: 9461
CVS date: 2006/05/03 07:54:38


Mercurial revision: e74d37bfc6663e1c3b210d5dd648050ecab5b6fe

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -24,20 +24,46 @@
 
 testProgram()
 {
-  if [ -z "$1" ]
-  then
-    return 0;
+  cmd=$1
+  WHICH_OPTS="-s"
+
+  if [ -z "$cmd" ]; then
+    return 1;
   fi
 
-  cmd=""
   arch=`uname -s`
-  if [ "$arch" = "Linux" -a "$arch" = "Darwin" ]
-  then
-    cmd="$1 --version </dev/null >/dev/null 2>&1"
-  else
-    cmd="which -s $1"
+  if [ "$arch" = "Darwin" ]; then
+      WHICH_OPTS=""
   fi
 
+  # Make sure the which is in an if-block... on some platforms it throws exceptions
+  #
+  # The ERR trap is not executed if the failed command is part
+  #   of an until or while loop, part of an if statement, part of a &&
+  #   or  ||  list, or if the command's return value is being inverted
+  #   via !.
+  if
+     ! which $WHICH_OPTS $cmd  </dev/null >/dev/null 2>&1
+  then
+      return 1
+  fi
+
+  # The GNU standard is --version
+  if 
+      $cmd --version </dev/null >/dev/null 2>&1
+  then
+      return 0 
+  fi
+
+  # Maybe it suppports -V instead
+  if 
+      $cmd -V </dev/null >/dev/null 2>&1
+  then
+      return 0 
+  fi
+
+  # Nope, the program seems broken
+  return 1
 }
 
 srcdir=`dirname $0`
@@ -76,9 +102,8 @@ pkg="autoconf"
 URL=$gnu/$pkg/
 for command in autoconf autoconf213 autoconf253 autoconf259 
 do
-  testProgram $command
   if
-	$cmd >/dev/null 2>&1
+      testProgram $command
   then
     : OK $pkg is installed
     autoconf=$command
@@ -111,9 +136,8 @@ pkg="automake"
 URL=$gnu/$pkg/
 for command in automake automake14 automake15 automake19 
 do
-  testProgram $command
   if 
-    $cmd  >/dev/null 2>&1
+      testProgram $command
   then
     : OK $pkg is installed
     automake=$command
@@ -142,9 +166,8 @@ pkg="libtool"
 for command in libtool libtool14 libtool15 glibtool
 do
   URL=$gnu/$pkg/
-  testProgram $command
   if
-    $cmd  >/dev/null 2>&1
+    testProgram $command
   then
     : OK $pkg is installed
     libtool=$command
