Fixed the standby option in the init script to handle the switch to auto_failback correctly.
CVS patchset: 2437
CVS date: 2004/02/08 09:32:30


Mercurial revision: c73dde4152f7413f11c7cd22f94caa6a720ef12a

diff --git a/heartbeat/init.d/heartbeat.in b/heartbeat/init.d/heartbeat.in
--- a/heartbeat/init.d/heartbeat.in
+++ b/heartbeat/init.d/heartbeat.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#	$Id: heartbeat.in,v 1.32 2004/01/20 15:35:09 alan Exp $
+#	$Id: heartbeat.in,v 1.33 2004/02/08 09:32:30 alan Exp $
 #
 # heartbeat     Start high-availability services
 #
@@ -266,31 +266,38 @@ StatusHA() {
 }
 
 StandbyHA() {
-  nice_failback=`ha_parameter nice_failback | tr "on" "ON"`
-  echo "nice_failback: $nice_failback"
+  auto_failback=`ha_parameter auto_failback | tr 'A-Z' 'a-z'`
+  nice_failback=`ha_parameter nice_failback | tr 'A-Z' 'a-z'`
+
+  case "$auto_failback" in
+    *legacy*)	echo "auto_failback is set to legacy.  Cannot enter standby."
+		exit 1;;
+  esac
+  case "$nice_failback" in
+    *off*)	echo "nice_failback is disabled.  Cannot enter standby."
+		exit 1;;
+  esac
+  case "${auto_failback}${nice_failback}" in
+    "")	echo "auto_failback defaulted to legacy.  Cannot enter standby."
+		exit 1;;
+  esac
+
+  echo "auto_failback: $auto_failback"
   if
-    [ "$nice_failback" = "ON" ]
+    StatusHA >/dev/null 2>&1
   then
+    EchoNoNl "Attempting to enter standby mode"
     if
-      StatusHA >/dev/null 2>&1
+      $HA_BIN/hb_standby
     then
-      Echo "Attempting to enter standby mode."
-      Echo
-      EchoNoNl "Attempting to enter standby mode"
-      if
-        $HA_BIN/hb_standby
-      then
-        # It's impossible to tell how long this will take.
-        echo_success
-      else
-        echo_failure $?
-      fi
+      # It's impossible to tell how long this will take.
+      echo_success
     else
-       Echo "Heartbeat is not currently running."
+      echo_failure $?
     fi
   else
-    Echo "Standby mode requires that nice_failback be enabled."
-    Echo "nice_failback is not enabled.  Cannot enter standby mode."
+    Echo "Heartbeat is not currently running."
+    exit 1
   fi
 }
 
@@ -388,6 +395,10 @@ exit $RC
 #
 #
 #  $Log: heartbeat.in,v $
+#  Revision 1.33  2004/02/08 09:32:30  alan
+#  Fixed the standby option in the init script to handle the switch to
+#  auto_failback correctly.
+#
 #  Revision 1.32  2004/01/20 15:35:09  alan
 #  Removed some old SuSE-isms from the init script.
 #
