do error checking
CVS patchset: 7287
CVS date: 2005/08/10 15:19:41


Mercurial revision: 563cd0257897d92fc43c45713f6bafefe63ae082

diff --git a/heartbeat/lib/hb_standby.in b/heartbeat/lib/hb_standby.in
--- a/heartbeat/lib/hb_standby.in
+++ b/heartbeat/lib/hb_standby.in
@@ -17,9 +17,17 @@ HA_DIR=@sysconfdir@/ha.d
 : Now running $0: $*
 
 usage() {
-	echo "usage: %0 [all|foreign|local|failback]" >&2
+	echo "usage: $0 [all|foreign|local|failback]" >&2
 	exit 1;
 }
+
+if
+  [ $# -ge 2 ]
+then
+        echo "$0: too many arguments"
+        usage
+        exit 1
+fi
 
 if
   [ $# -ge 1 ]
@@ -27,6 +35,13 @@ then
   resources=$1
 else
   resources=all
+fi
+
+if [ $resources != "all" ] && [ $resources != "foreign" ] &&
+   [ $resources != "local" ] && [ $resources != "failback" ]; then
+        echo "$0: wrong resource type ($resources). Maybe a typo?"
+	usage
+        exit 1
 fi
 
 case $resources in
diff --git a/heartbeat/lib/hb_takeover.in b/heartbeat/lib/hb_takeover.in
--- a/heartbeat/lib/hb_takeover.in
+++ b/heartbeat/lib/hb_takeover.in
@@ -14,9 +14,17 @@ HA_DIR=@sysconfdir@/ha.d
 . ${HA_DIR}/shellfuncs
 
 usage() {
-	echo "usage:%0 [all|foreign|local|failback]" >&2
-	exit 1;
+	echo "usage:$0 [all|foreign|local|failback]" >&2
 }
+
+if 
+  [ $# -ge 2 ]
+then
+	echo "$0: too many arguments"
+	usage
+	exit 1
+fi
+
 if
   [ $# -ge 1 ]
 then
@@ -25,6 +33,12 @@ else
   resources=all
 fi
 
+if [ $resources != "all" ] && [ $resources != "foreign" ] &&
+   [ $resources != "local" ] && [ $resources != "failback" ]; then
+	echo "$0: wrong resource type ($resources). Maybe a typo?"
+	usage
+	exit 1
+fi
 
 ha_clustermsg <<-!MSG
 	t=hb_takeover
