hb_standby/hb_takeover should not print error message for "--help" option
CVS patchset: 7292
CVS date: 2005/08/10 16:51:34


Mercurial revision: 3fa69daedcea7f128b68a672d726fdf9ef52e702

diff --git a/heartbeat/lib/hb_standby.in b/heartbeat/lib/hb_standby.in
--- a/heartbeat/lib/hb_standby.in
+++ b/heartbeat/lib/hb_standby.in
@@ -17,7 +17,8 @@ HA_DIR=@sysconfdir@/ha.d
 : Now running $0: $*
 
 usage() {
-	echo "usage: $0 [all|foreign|local|failback]" >&2
+	echo "usage:"
+	echo "$0 [all|foreign|local|failback]" >&2
 	exit 1;
 }
 
@@ -38,8 +39,9 @@ else
 fi
 
 if [ $resources != "all" ] && [ $resources != "foreign" ] &&
-   [ $resources != "local" ] && [ $resources != "failback" ]; then
-        echo "$0: wrong resource type ($resources). Maybe a typo?"
+   [ $resources != "local" ] && [ $resources != "failback" ] &&
+   [ $resources != "--help" ]; then
+        echo "$0: wrong resources($resources)."
 	usage
         exit 1
 fi
diff --git a/heartbeat/lib/hb_takeover.in b/heartbeat/lib/hb_takeover.in
--- a/heartbeat/lib/hb_takeover.in
+++ b/heartbeat/lib/hb_takeover.in
@@ -14,7 +14,9 @@ HA_DIR=@sysconfdir@/ha.d
 . ${HA_DIR}/shellfuncs
 
 usage() {
-	echo "usage:$0 [all|foreign|local|failback]" >&2
+	echo "usage:"
+	echo "$0 [all|foreign|local|failback]" >&2
+	exit 1
 }
 
 if 
@@ -33,9 +35,13 @@ else
   resources=all
 fi
 
+if [ $resources = "--help" ]; then
+	usage
+fi
+
 if [ $resources != "all" ] && [ $resources != "foreign" ] &&
    [ $resources != "local" ] && [ $resources != "failback" ]; then
-	echo "$0: wrong resource type ($resources). Maybe a typo?"
+	echo "$0: wrong resources($resources)."
 	usage
 	exit 1
 fi
